### ISSUE TITLE
Return 409 for write conflict

### ISSUE THREAD

**Issue by adriantam** [openfga/openfga#1080]
In some datastore, it is possible that write failed due to conflict (an example is if write is written as transaction and there are transaction conflict).  In these cases, it is better to return HTTP code 409 than internal error:

https://github.com/openfga/openfga/blob/d2b5f2d0ca472ddf565a90b747558046e89ea3bc/pkg/server/commands/write.go#L138-L140

**Comment by jon-whit** [comment]
Our protocol is gRPC. The HTTP API is derived off of this with the [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) project. We can choose to map a very specific kind of error to an alternative HTTP code, but the list of [gRPC status codes](https://grpc.github.io/grpc/core/md_doc_statuscodes.html) is much more finite than those in the HTTP world.

The closest code in gRPC would likely be the `ABORTED` code. See the guidance between `FAILED_PRECONDITION`, `ABORTED`, and `UNAVAILABLE` for more context.

It may help us to make the decisions if we focus on the "behavior" that we want instead. If a client calls the `Write`API and that write conflicts with another concurrent transaction, should the client retry? In our case we likely want the client to retry the transaction. If they retry the second request (e.g. the retried request, then it will likely return an error because the tuple will now exist due to the other concurrent write that was transacted. In this case I think ABORTED makes sense, because it will encourage the client to retry.
