### ISSUE TITLE
Add 2 level concurrent limit for check and list object

### ISSUE THREAD

**Issue by adriantam** [openfga/openfga#1082]
In our current implementation, OPENFGA_MAX_CONCURRENT_READS_FOR_CHECK and OPENFGA_MAX_CONCURRENT_READS_FOR_LIST_OBJECTS provides maximum concurrency limit for check and list objects.  In certain scenario (such as some caller invokes very expensive check and list objects), it may be beneficial to have a more aggressive concurrency limit if their request's datastore_query_count is above certain threshold.

**Comment by jon-whit** [comment]
@adriantam sorry but it's not clear what the idea is here. Could you elaborate? Are you suggesting that if the datastore query count is above a particular threshold then we apply a different concurrency setting for any subsequent sub-evaluations?

**Comment by adriantam** [comment]
Yes, this is what I am suggesting - we may need to explore how to protect server from very heavy request.

**Comment by miparnisari** [comment]
The concurrency limit is used to set the [size of a channel](https://github.com/openfga/openfga/blob/8dc2ed62413e7cccc7da57da057f1f1fc17dcb8a/pkg/storage/storagewrappers/boundedconcurrency.go#L42). I'm not sure it is possible to change that size after it's been created.

Could we change the title of this ticket to "ensure read-heavy checks are slowed down"? There are multiple ways of approaching this. We could apply heuristics, such as

- Once we hit `datastore_query_count > threshold`, wrap the datastore with yet another `BoundedConcurrencyTupleReader`
- Try to predict how complicated the query is upfront and reduce the concurrency limit right at the start

**Comment by jon-whit** [comment]
Let's make the goal clear here as well for anyone who may come along and read this later. 

> The idea is that we want to introduce a mechanism that allows Check evaluations to be throttled such that the rate at which we start evaluating _new_ Check subgraph evaluations is made more controllable. For this we will want to compare some metric representing current query cost (e.g. maybe we use `datastore_query_count` or a similar metric) and if we exceed that value then we start applying a throttle so as to reduce the processing rate of new subgraph evaluations.

We should rename this issue more generally to "Check Evaluation Throttling Based on Query Cost"

**Comment by jon-whit** [comment]
Thinking out loud here - The motivation behind this work is to help with the N*M query problem. The way I look at it this problem has 2 components, the cardinality/volume problem and the rate of expansion (e.g. subproblem evaluation) problem. Both are important, because they both lead to significant contention. 

Reducing the cardinality and volume problem by properly cancelling further expansion of subproblems is of upmost importance, because that’s how we reduce the dispatched calls altogether. 

But for further reliability we also need to reduce the rate of expansion when/if we encounter a query that leads to excessive expansion (e.g. at some point we hit a query expansion threshold and we need to start slowing the expansion down). The ultimate safe guard for us is the timeout of 3s, but if we don’t slow that expansion rate in an effective manner, then we can do a lot of saturation in 3s.

The purpose of this issue is to address the second bit ☝️ , but before doing so we really should make sure we're doing everything we can to reduce the cardinality problem first (reduce the breadth of N*M before tackling the expansion rate).

**Comment by adriantam** [comment]
Close in favour of dispatch and possibly datastore query throttling
