### ISSUE TITLE
Health Check should be in the Dockerfile and not docker-compose

### ISSUE THREAD

**Issue by ghstahl** [openfga/openfga#1117]
https://github.com/openfga/openfga/blob/0d38ae05f3de40773f6ba6afc66b18e59a5b9651/docker-compose.yaml#L51

Can we move this into the Dockerfile?

**Comment by jon-whit** [comment]
We have 2 docker files: `Dockerfile` and `Dockerfile.goreleaser`. The later is used in the goreleaser release process, and this is what our official images are built with. Since these official images are consumed in different ways outside of the docker ecosystem directly, I do not believe it makes sense to inclue a `HEALTHCHECK` directive in that docker file. I would encourage health checks be a more conscious decision by the community consuming the image. For example, if you're using the openfga image in a Kubernetes environment the `HEALTHCHECK` directive doesn't make sense and the readiness health check probes are more consciously defined.

For the `Dockerfile` case I feel it would be more appropriate to use the `HEALTHCHECK` directive. @ghstahl would you be willing to submit a PR for that? A contribution would be much appreciated.

**Comment by shaunco** [comment]
Since Kubernetes 1.8, the Docker HEALTHCHECK has been [disabled explicitly](https://github.com/kubernetes/kubernetes/pull/50796) in Kubernetes.

For Docker usage, it is very helpful to have the authors of a container be explicit about how one should check the health of that container - especially when the container might be built on scratch (no wget, no curl, no sh, etc), which means the container authors need to consciously include either a CLI option on their main binary to check the health or a second binary for health checking. Forcing users to Google "openfga healthcheck" to figure out what to do isn't a very good experience.
