### ISSUE TITLE
Enable List Objects API pagination

### ISSUE THREAD

**Issue by mamilic** [openfga/openfga#1298]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

When we want to implement REST API on microservice which can return all objects which belong to a User it is difficult to do so if there are a lot of objects. It would be much easier if we could fetch all objects by pagination included towards https://openfga.dev/api/service#/Relationship%20Queries/ListObjects endpont, so we can fetch objects from microservice database and return accordinly. Not sure if this is feasable from technical perspective, whether there are some constraints on OpenFGA.

### Describe the ideal solution

When fetching all Objects which user is associate with, it would be nice to have pagination avaliable.

**Comment by aaguiarz** [comment]
Hi @milic-marko 

How many tuples do you expect to retrieve? Did you try using the streaming list objects endpoint?

**Comment by milic-marko** [comment]
Hi @aaguiarz , 
Thank you for quick reply. I was wondering how could I use the streaming list objects, if you can give some guidelines? For following scenario, for example lets imagine that we are building the chat microservice, and we have million of groups something like let's say Whatsapp or Viber, and let's say that user can be part of N groups, and in order to improve performance the pagionation would be perfect fit and load conversations based on page number and number of items per page.

And when the mobile or web app, fetch all conversations it needs to execute GET request towards **users/{userId}/conversations**
And there if we want to use OpenFGA the service needs to find all conversations which user has relation to. Would it be feasable to contact the listObjects API and set the pagination which would be included in initial call to REST API, and with object ids returned from OpenFGA to just fetch all conversations from database of the service?

**Comment by aaguiarz** [comment]
Thanks @milic-marko 

Let's dig a little more in the example. Following the Whatsapp example, are conversations "messages" or "groups"? 

If you need to display the conversations to the user, do you need them ordered in a certain way? e.g. by date?

**Comment by milic-marko** [comment]
Hi @aaguiarz ,

Sorry for confusion.
Let's say they are group/chat/conversation and each group/chat/conversation can have N messages related to.
And we want to sort them by date or a title/name.

**Comment by milic-marko** [comment]
Also there is one interesting thread describing this scenario here, https://softwareengineering.stackexchange.com/questions/418588/api-pagination-with-external-or-centralised-authorization.

What are your thoughts, what would be the best approach?
