### ISSUE TITLE
list objects with filter

### ISSUE THREAD

**Issue by jaredzhou** [openfga/openfga#301]
after reading [Search with Permission](https://openfga.dev/docs/interacting/search-with-permissions), i find it is nature to use `Build A List Of IDs, Then Search` pattern in some senario, but if the number of objects is too big, that's not practical. and i wonder can we add some kind of filter for `GET /list-objects`, so we can use this pattern for wide. for example, the model 
```
type document
  relations
    define parent as self
    define editor as self
type folder
  relations
    define viewer as self
```
if i want to search for docs  object ids, it may be big, but what if i want to search for docs object ids who's parent is `folder:a`, i think if the api can provide this, we can use this pattern in a lot more scenarios. maybe like this
```go
body := fgaSdk.ListObjectsRequest{
    User:                 PtrString("bob"),
    Relation:             PtrString("reader"),
    Type:                 PtrString("document"),
    FilterTuples: &FilterTupleKeys{
        TupleKeys: []TupleKey{{
            User:     PtrString("folder:a"),
            Relation: PtrString("parent"),
        },
    },
}

data, response, err := apiClient.OpenFgaApi.ListObjects(context.Background()).Body(body).Execute()
```
i wonder if this is possible to implement

**Comment by jon-whit** [comment]
I understand what you're trying to do, but my initial gut reaction is that this would be quite difficult and nuanced. In the scenario you gave the relations are direct relations, but what if the relation the developer wants to filter by is not a direct relation (e.g. it involves rewrites other than `as self`). There is some complex nuance to this, and I think it warrants more discovery and research before we can confidently say anything about supporting it or not supporting it.

In general, supporting this may require a costly sub-query evaluation before the top-level query can be resolved, and the top-level query would somehow have to be able to traverse the graph in reverse in a filtered form (where the filtered traversal is impacted by the sub-query). Not saying it’s not possible, but it’s definitely more complex for the general case than this simple model demonstrates.

We'll keep an open mind and see if we can come up with something 👍

**Comment by jaredzhou** [comment]
thank you for the response. i don't think we need to support the filter like `check` that indirect relation and rewrite involved, at least not a must.  users just need to add some object-to-objects relations to be used like tags to some objects, and it even can be nothing to do with auth check, when query the `GET /list-objects` api, it can be simply filtered by tags and reduce the number of returned ids

**Comment by jaredzhou** [comment]
i have not reading the code details, but for my understanding, it's like the intersect result of two sets. the origin object ids set and   the filtered object ids set which only produced by direct object-to-object relations

**Comment by jon-whit** [comment]
> thank you for the response. i don't think we need to support the filter like `check` that indirect relation and rewrite involved, at least not a must. users just need to add some object-to-objects relations to be used like tags to some objects, and it even can be nothing to do with auth check, when query the `GET /list-objects` api, it can be simply filtered by tags and reduce the number of returned ids

I'm not sure I understand what you mean here. Relationships in OpenFGA don't have a tagging/metadata mechanism like you are describing, but rather the relationships themselves establish connectivity between objects in the graph of relationships. Maybe you could provide a more clear example that demonstrates the situation (with tuples etc..)?

In your original example you mentioned filtering the set of `document#reader` relationships that a user `bob` has based on a parent relationship with some folder `folder:a`. If `folder#parent` relationships involved more than just a direct relation to documents though (like some other relationships might), then it would require a filtered expansion (see the [Expand API](https://openfga.dev/api/service#/Relationship%20Queries/Expand)) of the relationship(s) before an intersection of the two sets could be computed for the filtered set. This could be quite costly to compute server side within the scope of the request.

This problem is much more nuanced and challenging than one might think. If, on the other hand, you are referring to some other process where you label/categorize relationships with other metadata and then filter based on that metadata, then that may be something that we could potentially look into. I'm not sure what exactly that would look like in general usage though..

**Comment by jaredzhou** [comment]
yes, this is exactly what i mean. i described it as tags but implemented by object-to-object relationships.  considering the complexity for implementing indirect relations for filtering. i think just filtering by direct object-to-object relationship maybe easier to do. for usage, users can insert the object-to-object relationships for particular usage. e.g. insert parent-child file relationship for list files in certain folders. for more scenario, i think resources that potentially has large amount totally, but can has reasonable amount under some tags.

**Comment by aaguiarz** [comment]
We are not going to pursue this for the time being
