### ISSUE TITLE
Read tuples specifying only user

### ISSUE THREAD

**Issue by kian99** [openfga/openfga#463]
Using the read API I would like to query for all tuples where the user is a specific resource e.g. "group:MyGroup"

This would be useful when we want to remove a group or any generic object.

I imagine this might be more complex than requested since it's not available already, in which case is there any suggested way to remove resources that can be a user/object (without querying for all tuples)?

**Comment by jon-whit** [comment]
The OpenFGA maintainer team has discussed making the Read API more generic so that you can filter tuples from various "angles". Right now the best way to do this would be to either query all of the tuples (not ideal) OR you could query all of the tuples for the specific user object for each of the object types in the system. For example, to find all of the tuples for `user:jon` in the system you could find all of the tuples for `folder` and `document` objects related to `user:jon`:

```
type user

type document
  relations
    define viewer: [user]

type folder
  relations
    define viewer: [user]
```

```
POST /stores/:storeId/read
{
 "tuple_key": {
     "user": "user:jon",
     "object": "document:"
  }
}
```
followed by
```
POST /stores/:storeId/read
{
 "tuple_key": {
     "user": "user:jon",
     "object": "folder:"
  }
}
```

then delete all of the tuples from these two independent requests.

**Comment by kian99** [comment]
Thanks for this! The way forward makes sense and is what I was expecting.

Just my 2 cents, but it would be very beneficial for the Read API to be more flexible so that queries from both "sides" of the relationship are possible. 
- It feels more intuitive when queries on the user side can be done similarly to the object side. 
- Further, in my specific scenario, where there are say 4+ different object types then the queries can become a bit excessive. 
- Finally it allows for a more generic implementation, on my application side, for removing a resource, i.e. removing a document will only ever require a query on the "object" side but removing a group would require queries on both sides (user and object), since a group could be a member of another group.

**Comment by rhamzeh** [comment]
Related: https://github.com/openfga/openfga/issues/337

**Comment by aaguiarz** [comment]
Added to the roadmap https://github.com/openfga/roadmap/issues/33
