### ISSUE TITLE
gRPC server not accessible outside of docker

### ISSUE THREAD

**Issue by MidasLamb** [openfga/openfga#74]
Currently, the gRPC server is exposed on port 8081, however that is only bound to localhost (and thus only reachable within the docker container itself, and not from the outside).
The docker image itself exposes port 8081, so it seems that it would be the intention that the gRPC server itself is bound to `0.0.0.0:8081` rather than `localhost:8081`.
It might be nice that this is configurable through e.g. an env variable, in case users don't want to expose the gRPC server.

**Comment by jon-whit** [comment]
@MidasLamb you are right. We plan on changing this so that you can provide a server bind address that the HTTP and grpc servers start up on. That will be configurable. I'll keep this open and cross reference the PR so you can track progress on that.

Thanks for reporting this, it helps us prioritize this work a bit 👍🏻.
