### ISSUE TITLE
Improve `Check` speed by pruning userset lookups that cannot result in success

### ISSUE THREAD

**Issue by jbrooks2-godaddy** [openfga/openfga#852]
The introduction of the `1.1` type system in model definitions paved the way for `Check` performance improvements. Some were implemented here: https://github.com/openfga/openfga/pull/545

I believe that we can build upon the changes introduced in that PR and use the type information to further prune and short-circuit userset lookups that cannot result in access being granted.

Consider this toy authorization model:
```
model
  schema 1.1
type user
type oauth_client
type document
  relations
    define owner: [user]
    define can_write: [oauth_client] or owner
```

And a `Check` request:
```
POST /check:
{
  "tuple_key": {
    "user": "oauth_client:123",
    "relation": "can_write",
    "object": "document:abc"
  }
}
```

The `Check` system ends up doing two things to resolve this in [`CheckDirect`](https://github.com/openfga/openfga/blob/main/internal/graph/check.go#L371-L511):
1. Checking the direct relationship; querying the database for the full `< document:abc, can_write, oauth_client:123 >`
2. Checking the userset relationship; querying the database for the list of tuples satisfying `object=document:abc, relation=owner`

https://github.com/openfga/openfga/pull/545 made some changes that improved both of these parts:
- (1) is completely avoided if the type definition makes the relationship impossible
- (2) passes a type filter to the storage system; instructing it to return fewer tuples.

I think that for some models, (2) can be short-circuited in a way similar to (1). In this example authorization model, an `oauth_client` cannot be an `owner` of a `document`. If the type system can be used to understand this restriction, then we can avoid a db call completely for (2).

**Comment by jon-whit** [comment]
Yep, definitely. The relationship ingresses can be used to prune the search space. It's something we're aware of and have talked about adding optimizations for. We've also been working on the storage layer to reduce/filter the related types at the query layer. That will help as well.

**Comment by jon-whit** [comment]
Just to elaborate on my last comment for any future readers.. Imagine you have a model such as

```
type user

type employee

type group
  relations
    define member: [employee]

type document
  relations
    define viewer: [user, group#member]
```

If you call `Check(document:1#viewer@user:jon)`, then the evaluation path for `group#member` relationships with `document#viewer` is an unecessary path in the search because there is no path in that subgraph that leads from `document#viewer` through `group#member` to a `user` object. `group#member` is only directly related to `employee` object types, and so there would not exist any path leading to a `user` object type from that subgraph.

We refer to these paths of connectivity in the graph of relationships as "relationship ingresses" or entrypoints. The ingress' from some source to some target are the paths that connected via directly related user types as you expand the graph.

**Comment by adriantam** [comment]
See https://github.com/openfga/openfga/issues/852
