### ISSUE TITLE
Default config prints a warning(?) to straight to STDOUT without logger

### ISSUE THREAD

**Issue by KlausVii** [openfga/openfga#922]
I am confused by these 2 lines, are they meant to return errors or print a warning with the logger? 

https://github.com/openfga/openfga/blob/main/cmd/run/run.go#L474
https://github.com/openfga/openfga/blob/main/cmd/run/run.go#L470

Additionally since the defaults for `MaxConcurrentReadsForCheck` and `Datastore.MaxOpenConns` are `MaxUint32` and `30` respectively, this prints every time the application is run with default options.

**Comment by miparnisari** [comment]
Hey @KlausVii, thanks for the report. We're thinking about removing those logs since, if using the defaults, the only issue will be that reads will be throttled because you can't have more than `Datastore.MaxOpenConns` queries executing at once against the database. 

We could also set `Datastore.MaxOpenConns` to also be `MaxUint32`.

My idea behind either option is for people to realize that to get the best performance they need to change the defaults according to their deployment (e.g. how many replicas? how many connections can the database hold? are there other apps running against the database? how much traffic do you expect?)

What do you think?

**Comment by KlausVii** [comment]
Thanks for the reply @miparnisari

I was mostly confused because that function returned an error for all the other cases within it that caused the application to fail to start and because it used fmt.Printf instead of the logger causing the warnings to not follow log format. 

We had our logger set to json, and so these logs showed up as unparsed by our log aggregator.

I'm not sure what the correct default configuration should be, though maybe just not setting `MaxOpenConns` could be reasonable (that's what the std library does and it should work for most people). I would expect an application's default configuration to run with decent performance and minimal warnings on a typical deployment.

**Comment by miparnisari** [comment]
The warning was removed in https://github.com/openfga/openfga/pull/1036

**Comment by miparnisari** [comment]
Closing, this was released in 1.3.3
