### ISSUE TITLE
[feature] Add perishable tuple (expiration date time)

### ISSUE THREAD

**Issue by le-yams** [openfga/openfga#961]
Hello There,

We have a use case where we want to create a tuple but for a given amount of time.
Would it be something that openfga could support (maybe it deserves an RFC)?

Regards,
Yann

**Comment by rhamzeh** [comment]
Thanks for raising the issue @le-yams!

We are working on this as part of our improved ABAC support https://github.com/openfga/roadmap/issues/32

That would allow you to add context to tuples and add conditions that would evaluate the context in order for a relationship to be valid.

Timestamps will be one of the possible values to context, and you can add a condition that would return true if the period since that timestamp is greater than some value.

**Comment by le-yams** [comment]
Great news! And sorry I missed that.
Thanks a lot  :)

**Comment by rhamzeh** [comment]
You can find a very early demo of this work here: https://youtu.be/sFqk42fJy_E?t=665

Please let us know if you have any feedback!
